### ISSUE TITLE
Go through publications list to update links and clean

### ISSUE THREAD

**Issue by smash0190** [castacks/website-dev#20]
- Make sure that format is correct and consistent
- Add DOI links
- Add links to  RI website PDF files or  pdfs in  our repo
- Add abstracts

**Comment by bradygm** [comment]
A point of clarification here is that the pdf link should link straight to a pdf and not the arxiv page or ri page. It should open the pdf itself.

**Comment by smash0190** [comment]
Added as many as I could find.
