### ISSUE TITLE
Check all paper references that are just ArXiv papers that there isn't an actual published version of it. 

### ISSUE THREAD

**Issue by bradygm** [castacks/website-dev#56]
We might have duplicated publications where there is an arxiv version as well as the published version.

**Comment by seeeheng** [comment]
Notes for me to amend the publications.

Robust Modeling and Controls for Racing on the Edge
By Spisak, J., Saba, A., Suvarna, N., Mao, B., Zhang, C.T., Chang, C., Scherer, S. and Ramanan, D.
2022 Opportunities and Challenges in Autonomous Racing, International Conference on Robotics and Automation (ICRA)

Integration of Fully-Actuated Multirotors into Real-World Applications
- No information on publication

A Robust Laser-Inertial Odometry and Mapping Method for Large-Scale Highway Environments.
By Zhao, S., Fang, Z., Li, H.L. and Scherer, S.
2019 IEEE/RSJ International Conference on Intelligent Robots and Systems, IROS 2019

Do You See What I See? Coordinating Multiple Aerial Cameras for Robot Cinematography.
By Bucker, A., Bonatti, R. and Scherer, S.
2021 IEEE International Conference on Robotics and Automation (ICRA)
https://ieeexplore.ieee.org/document/9561086

Batteries, camera, action! Learning a semantic control space for expressive robot cinematography.
By Bonatti, R., Bucker, A., Scherer, S., Mukadam, M. and Hodgins, J.
2021 IEEE International Conference on Robotics and Automation (ICRA)
https://ieeexplore.ieee.org/document/9560745

**A Stereo Algorithm for Thin Obstacles and Reflective Objects.
By Keller, J. and Scherer, S.
In arXiv.org, Oct. 2019.
- rejected **

LiDAR Enhanced Structure-from-Motion
By Zhen, W., Hu, Y., Yu, H. and Scherer, S.
2020 IEEE International Conference on Robotics and Automation (ICRA)
https://ieeexplore.ieee.org/document/9197030

**Learning Controls Using Cross-Modal Representations: Bridging Simulation and Reality for Drone Racing.
By Bonatti, R., Madaan, R., Vineet, V., Scherer, S. and Kapoor, A.
In arXiv.org, Sep. 2019.
(No Info)**

Autonomous Aerial Cinematography In Unstructured Environments With Learned Artistic Decision-Making.
By Bonatti, R., Wang, W., Ho, C., Ahuja, A., Gschwindt, M., Camci, E., Kayacan, E., Choudhury, S. and Scherer, S.
Journal Article, Journal of Field Robotics, Vol. 37, No. 4, pp. 606 - 641, June, 2020 

**Hindsight is Only 50/50: Unsuitability of MDP based Approximate POMDP Solvers for Multi-resolution Information Gathering.
By Arora, S., Choudhury, S. and Scherer, S.
In arXiv.org, Apr. 2018.
[no info]**

** Monocular and Stereo Cues for Landing Zone Evaluation for Micro UAVs.
By Garg, R., Yang, S. and Scherer, S.
In arXiv.org, Dec. 2018.
[no info] **

**Open Problems in Robotic Anomaly Detection.
By Gupta, R., Kurtz, Z.T., Scherer, S. and Smereka, J.M.
In arXiv.org, Sep. 2018.
[no info] **

Autonomous drone cinematographer: Using artistic principles to create smooth, safe, occlusion-free trajectories for aerial filming.
By Bonatti, R., Zhang, Y., Choudhury, S., Wang, W. and Scherer, S.
In arXiv.org, Aug. 2018.
International Symposium on Experimental Robotics (ISER) 2018

** Obstacle Avoidance through Deep Networks based Intermediate Perception.
By Yang, S., Konam, S., Ma, C., Rosenthal, S., Veloso, M. and Scherer, S.
In arXiv.org, Apr. 2017.
[no info] **

Robust Localization of an Arbitrary Distribution of Radioactive Sources for Aerial Inspection.
By Shah, D. and Scherer, S.
Sensors, 2018
https://www.mdpi.com/1424-8220/18/11/3784

Direct Monocular Odometry Using Points and Lines.
By Yang, S. and Scherer, S.
2017 IEEE International Conference on Robotics and Automation (ICRA)
https://ieeexplore.ieee.org/document/7989446

Bayesian Active Edge Evaluation on Expensive Graphs
By Choudhury, S., Srinivasa, S. and Scherer, S.
IJCAI'18: Proceedings of the 27th International Joint Conference on Artificial Intelligence
https://dl.acm.org/doi/10.5555/3304652.3304689

Near-Optimal Edge Evaluation in Explicit Generalized Binomial Graphs
By Choudhury, S., Javdani, S., Srinivasa, S. and Scherer, S.
Advances in Neural Information Processing Systems 30 (NIPS 2017) 
https://papers.nips.cc/paper/2017/hash/e139c454239bfde741e893edb46a06cc-Abstract.html

Learning Heuristic Search via Imitation.
By Bhardwaj, M., Choudhury, S. and Scherer, S.
1st Conference on Robot Learning (CoRL 2017)
http://proceedings.mlr.press/v78/bhardwaj17a/bhardwaj17a.pdf

**Comment by seeeheng** [comment]
@bradygm Once I've checked with the authors, do I remove publications that were not accepted to any conference but still have a number of citations? Or do I leave them with the arxiv link?

**Comment by bradygm** [comment]
@seeeheng you can leave publications that are only on arXiv and were never published. This issue is mainly about updating the references that were first uploaded as the arXiv version on our website and then never updated. 

Thanks!

**Comment by smash0190** [comment]
Completed the review. Up-to-date as of 1/16/2024
