### ISSUE TITLE
Add youtube and linkedin links

### ISSUE THREAD

**Issue by bradygm** [castacks/website-dev#70]
Maybe remove facebook?

**Comment by bradygm** [comment]
I added the linkedin link this morning. I didn't see it was on this issue :)

**Comment by smash0190** [comment]
Should we close this?

**Comment by bradygm** [comment]
All that needs to be done is remove the facebook link and add the youtube link. Probably a 10 minutes task. @seungchan-kim, could you finish this this week?

**Comment by bradygm** [comment]
Fixed @3c0ae3f8776c8fd0747bad276e8dd04ab584b966
